name = "example"
description = ""
version = "0.1.0-dev"

authors = ["H. ROMANO"]
maintainers = ["H. ROMANO <shuihuzhuan@free.fr>"]
maintainers-logins = ["HROMANO"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["example"]

[[depends-on]]
i18n = "*"

[[pins]]
i18n = { path='..' }
